baseURL: https://babble.matthewroll.com
languageCode: en-us
title: babble
theme: noteworthy

taxonomies:
  tag: "tags"

author:
  name: "matt roll"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - name: Archives
      identifier: archives
      url: /archives/
      weight: 4


params:
  # Site Author
  author: Matt Roll
  # Author biography
  bio: ''
  # Site Description, used in HTML meat
  description: "to write better, write more"
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: false
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: false

  # Optional
  home: '' # Default: Home
  about: '' # Default: About
  archive: '' # Default: Archive
  tags: '' # Default: Tags
  subscribe: '' # Default: Subscribe
  olderPosts: '' # Default: Older Posts
  newerPosts: '' # Default: Newer Posts
  copyright: '' # Default: © Copyright 2021 ❤️ author
  title404: '' # Default: 404 - Page Not Found
  subtitle404: '' # Default: The content you're looking for doesn't seem to exist.
  readMore: '' # Default: Read More

  # Extra links in navigation
  links:
    # e.g.
    # - name: Project
    #   path: /project
